//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleEchoBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleEchoBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklager, jeg forstår ikke helt hva du mener..
        /// </summary>
        internal static string CannotUnderstand {
            get {
                return ResourceManager.GetString("CannotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bli kontaktet.
        /// </summary>
        internal static string ContactMe {
            get {
                return ResourceManager.GetString("ContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vil du at {0} skal kontakte deg?.
        /// </summary>
        internal static string ContactQuestion {
            get {
                return ResourceManager.GetString("ContactQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg er ikke så smart at jeg forstår alt ennå, men jeg er flink til å hjelpe deg med Ressurs, Bransje eller Tjeneste..
        /// </summary>
        internal static string FallbackQuestion {
            get {
                return ResourceManager.GetString("FallbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nei takk, jeg tar kontakt selv.
        /// </summary>
        internal static string IllContact {
            get {
                return ResourceManager.GetString("IllContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flott. Kontaktdetaljene ser du i kortet over..
        /// </summary>
        internal static string IllContactResponse {
            get {
                return ResourceManager.GetString("IllContactResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bransje.
        /// </summary>
        internal static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flott! KPMG har god innsikt i hvilke særskilte utfordringer de ulike bransjene står ovenfor. Håper du kan ha nytte av vår bransjeinnsikt..
        /// </summary>
        internal static string IndustryChosen {
            get {
                return ResourceManager.GetString("IndustryChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er en bransje under stort effektiviseringspress om dagen. Jeg foreslår at vi setter deg i kontakt med {1}, som ekspert på området..
        /// </summary>
        internal static string IndustryChosen2 {
            get {
                return ResourceManager.GetString("IndustryChosen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg hvilken sektor du er interessert i under, så skal vi hjelpe deg videre..
        /// </summary>
        internal static string IndustryQuestion {
            get {
                return ResourceManager.GetString("IndustryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei, jeg er KPMGs automatiske meldingstjeneste. Hvis du velger det området henvendelsen gjelder under, så skal jeg hjelpe deg videre..
        /// </summary>
        internal static string InitialQuestion {
            get {
                return ResourceManager.GetString("InitialQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklager! Det vet jeg ikke noe om enda..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressurs.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flott! KPMG tilbyr tjenester innenfor en rekke områder..
        /// </summary>
        internal static string ServiceChosen {
            get {
                return ResourceManager.GetString("ServiceChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er et av KPMGs tjenesteområder. Jeg foreslår at vi setter deg i kontakt med {1}, som ekspert på området..
        /// </summary>
        internal static string ServiceChosen2 {
            get {
                return ResourceManager.GetString("ServiceChosen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg hvilket tjenesteområde du er interessert i under..
        /// </summary>
        internal static string ServiceQuestion {
            get {
                return ResourceManager.GetString("ServiceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg kan desverre bare svare på spørsmålet over foreløpig. Vennligst velg et av alternativene..
        /// </summary>
        internal static string SorryChoose {
            get {
                return ResourceManager.GetString("SorryChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flott. Vår medarbeider vil ta kontakt så snart som mulig..
        /// </summary>
        internal static string YouWillBeContacted {
            get {
                return ResourceManager.GetString("YouWillBeContacted", resourceCulture);
            }
        }
    }
}
